// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_r6wEb2uvV5mjZN_ruEE9cJeJYMF5CLc',
    appId: '1:929721104545:web:cc414db9e5413f7fbc58e0',
    messagingSenderId: '929721104545',
    projectId: 'nrl-championship',
    authDomain: 'nrl-championship.firebaseapp.com',
    storageBucket: 'nrl-championship.firebasestorage.app',
    measurementId: 'G-HS8RS32XNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl2MdUqinuKaGgZYIetDLqk83e9cMI1Ks',
    appId: '1:929721104545:android:b93bd49c98610e74bc58e0',
    messagingSenderId: '929721104545',
    projectId: 'nrl-championship',
    storageBucket: 'nrl-championship.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH43DUVaXfZdSiS-df3GQ6lyKRXcZeQCI',
    appId: '1:929721104545:ios:0cff76ca72aa0eb2bc58e0',
    messagingSenderId: '929721104545',
    projectId: 'nrl-championship',
    storageBucket: 'nrl-championship.firebasestorage.app',
    iosBundleId: 'com.example.nrlApp',
  );
}
